env:
  M2W_VERSION: latest

name: m2w-example
on:
  push:
    paths:
      - 'posts/*'
    branches:    
      - main
      - dev
jobs:
  push:
      runs-on: ${{ matrix.operating-system }}
      strategy:
        matrix:
          # in this example, there is a newer version already installed, 3.7.7, so the older version will be downloaded
          operating-system: ['ubuntu-20.04']
      steps:
      - uses: actions/checkout@v2 # Checking out the repo
      - name: Pull m2w code
        run: |
          wget https://cdn.jsdelivr.net/gh/cye18/m2w@$M2W_VERSION/pyproject.toml
          wget https://cdn.jsdelivr.net/gh/cye18/m2w@$M2W_VERSION/pdm.lock
          wget https://cdn.jsdelivr.net/gh/cye18/m2w@$M2W_VERSION/main.py
          wget https://cdn.jsdelivr.net/gh/cye18/m2w@$M2W_VERSION/utils.py
      - name: Run with setup-python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install pdm
        run: pip install pdm
      - name: Install dependecies
        run:  |
          pdm sync
      - name: Build
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          XMLRPC_PHP: ${{ secrets.XMLRPC_PHP }}
          ENABLE_DELETION: ${{ secrets.ENABLE_DELETION }}
        run: pdm run python main.py
      - name: Commit and push if changed   # 将.md_sha1 README.md 更新到仓库
        run: |
          git diff
          git config --global user.email "chengweiye18@gmail.com"
          git config --global user.name "cye18"
          git add .md_sha1 README.md
          git commit -m "Github Action auto Updated"
          git push